### ISSUE TITLE
timestamp resolution on windows

### ISSUE THREAD

**Issue by hansvanthag** [eclipse/cyclonedds#33] opened 2018-11-01 12:26 UTC
The roundtrip-example, when run on windows displays only zero's for min/mean roundtrip-times.
This is most likely due to using a clock with insufficient resolution

**Comment by eboasson** [comment] 2018-11-05 08:04
I think that means it is using ``GetSystemTimeAsFileTime`` instead of ``GetSystemTimePreciseAsFileTime``. The latter function is available starting with Windows 8, but based on my reading of the source and Microsoft's documentation, I think it got some checks wrong.

Hopefully it will be be better with: https://raw.githubusercontent.com/eboasson/cyclonedds/windows-time/src/os/src/windows/os_platform_time.c 

Perhaps you could check it actually works as intended before I commit it here?

**Comment by hansvanthag** [comment] 2018-11-05 09:08
Definately an improvement, still strange that the Read-access times are (still) all reported as '0'.

Here are some single-node (loopback) results on my win10 laptop (i7-8550U@1.80Ghz):

# Latency measurements (in us)
#             Latency [us]                                   Write-access time [us]       Read-access time [us]
# Sec     Count   median   min     99%   max      Count   median   min   Count   median  min
        1     30647       17       12       22      341      30647       13        8      30647        0        0
        2     32219       16       12       20      363      32219       12       11     32219        0        0
        3     31612       16       12       21        51      31612       12       11     31612        0        0
        4     32380       16       12       20        50      32380       12       11     32380        0        0
        5     33780       13       12       19        67      33780       12       11      33780        0        0
        6     33970       13       12       20      811      33970       12       11      33970        0        0
        7     33262       14       12       22      138      33262       12       11      33262        0        0

**Comment by hansvanthag** [comment] 2018-11-05 10:12
using a size of 32K indeed shows >0 us. read-access times:

    sec          count    median  min     99%    max       write:    median  min     read:     median min
  Overall     84070      130       94      175     6420      84070      103       89      84070        2        1

**Comment by eboasson** [comment] 2018-11-05 11:12
Thanks for confirming it works, I've merged the change into the master branch.

**Closed by eboasson** 2018-11-05 11:12 UTC
